### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by Ansem93** [OpenMediaVault-Plugin-Developers/openmediavault-wakealarm#6]
Hi everyone,
I have installed wakealarm 3.4 on OMV 4.1.4 with a backport of kernel 4.14. but during the installation I got this error:

```
    Processing triggers for rsyslog (8.24.0-1) ...
    Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f7f3bc4c8c8>
    Traceback (most recent call last):
      File "/usr/lib/python3.5/weakref.py", line 117, in remove
    TypeError: 'NoneType' object is not callable
    Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f7f3bc4c8c8>
    Traceback (most recent call last):
      File "/usr/lib/python3.5/weakref.py", line 117, in remove
    TypeError: 'NoneType' object is not callable
    Done ...

```

How can I resolve it? :( Do i need to wait for an update?

**Comment by subzero79** [comment]
This a bug in the Debian python package. Check the forum.
